### ISSUE TITLE
jfind not working with the dev versions of neovim

### ISSUE THREAD

**Issue by Sawansunar56** [jake-stewart/jfind.nvim#20]
Jfind seems to not work for the dev versions of neovim. I was using it perfectly fine till I installed the latest version of neovim and somehow it has stopped working entirely and the error it produces is truncated as well so I am kinda lost. 

Please help me fix this problem. 

Neovim Version:
NVIM v0.10.0-dev-1f551e0
Build type: Release
LuaJIT 2.1.1694466036

Problem description:
1) Open Neovim 
2) Press <M-f> to call jfind and it opens up
3) Pressing enter in the result causes the error below to show up in cmd.

Problem Image:
![Screenshot 2023-09-14 021939](https://github.com/jake-stewart/jfind.nvim/assets/62794662/4a32da05-51f8-41a1-b898-894fa094b804)

**Comment by jake-stewart** [comment]
from the small information in the screenshot, we can see that the problem originates in this part of the code:

```lua
    vim.fn.termopen(cmd, {on_exit = function(_, status, _)
        vim.api.nvim_win_close(win, 0)
        if status == 0 then
            onComplete()
        end
    end})
```

i am unable to replicate the bug. i believe it is a neovim bug since you are using dev.

can you run this lua script and tell me what happens?

```lua
lua local buf = vim.api.nvim_create_buf(false, true)
local ui = vim.api.nvim_list_uis()[1]
local opts = {
    relative="editor",
    col = 1,
    row = 1,
    width = 60,
    height = 20
}
local win = vim.api.nvim_open_win(buf, 1, opts)
vim.fn.termopen("bash", {
    on_exit = function(_,status,_)
        vim.api.nvim_win_close(win, 0)
        if status == 0 then
            print("done")
        end
    end
})
```

**Comment by Sawansunar56** [comment]
I am very Sorry about the delay, I was not free for the remaining week. And I got sometime to use the code you provided(I directly added it to my jfind config).

I got something like this
![Screenshot 2023-09-17 200748](https://github.com/jake-stewart/jfind.nvim/assets/62794662/1053f3c7-16f7-4bfd-8ba3-6daadf0615c8)

**Comment by Sawansunar56** [comment]
@jake-stewart I do seem to get warnings like these in the code itself. 

![Screenshot 2023-09-17 201029](https://github.com/jake-stewart/jfind.nvim/assets/62794662/cd866221-6b77-48a3-8faf-eb1e39c7eb59)

**Comment by jake-stewart** [comment]
@Sawansunar56 try change the 1 to be `true` and the 0 to be `false`.

if that fixes it then i'll push it to main

**Comment by Sawansunar56** [comment]
If you meant in the jfind init then it does not fix the problem, also I tried that before I made the issue and even now but, nothing. I did however find some other warnings at line 126, 151 and 257. The former two show the same error while 257 is "Duplicate field 'callback'".

![Screenshot 2023-09-18 004145](https://github.com/jake-stewart/jfind.nvim/assets/62794662/ac007e48-8ff7-44e8-a5fb-fdbadd8526e0)

**Comment by jake-stewart** [comment]
@Sawansunar56 i pushed changes to the `2.0` branch which fixes the bools and the deprecation warning.

can you test it out and tell me if it works? you can just update it with your plugin manager

**Comment by Sawansunar56** [comment]
I tried the update but it did not fix the problem, I reinstalled jfind and updated neovim, nothing worked for me. Also, I think I got the same error as before. 


![Screenshot 2023-09-18 134612](https://github.com/jake-stewart/jfind.nvim/assets/62794662/9b1cefb1-8528-487f-8654-0dcad34c7ec1)
The mentioned lines
![Screenshot 2023-09-18 134652](https://github.com/jake-stewart/jfind.nvim/assets/62794662/70b3c34b-e1ca-4b19-88c7-aae48f2a4242)

**Comment by Sawansunar56** [comment]
> I tried the update but it did not fix the problem, I reinstalled jfind and updated neovim, nothing worked for me. Also, I think I got the same error as before.
> 
> ![Screenshot 2023-09-18 134612](https://user-images.githubusercontent.com/62794662/268589230-9b1cefb1-8528-487f-8654-0dcad34c7ec1.png) The mentioned lines ![Screenshot 2023-09-18 134652](https://user-images.githubusercontent.com/62794662/268589282-70b3c34b-e1ca-4b19-88c7-aae48f2a4242.png)

Is there some way to expand the error message?

**Comment by jake-stewart** [comment]
@Sawansunar56 you could try `set cmdheight=20` but other than that not sure
if you're up for it, add me on discord at jake_stewart and you could share your screen so we can debug this

**Comment by Sawansunar56** [comment]
@jake-stewart I was able to fix this problem. Funny enough, it was related to a single line of code.  

![Screenshot 2023-09-18 193525](https://github.com/jake-stewart/jfind.nvim/assets/62794662/2fc10a5b-1a11-4c1f-a606-844c8d15e4f7)

I realized this when I was able to get the full error message through `:messages` command
![Screenshot 2023-09-18 193640](https://github.com/jake-stewart/jfind.nvim/assets/62794662/86dd0d49-13d9-4c8d-ae76-b9c6be1b41ec)

I do not know if it breaks other things or not but for me everything seems to be working fine.

**Comment by jake-stewart** [comment]
@Sawansunar56 do you possibly have an autocommand which automatically closes terminal windows?

**Comment by jake-stewart** [comment]
this is very strange. if i comment that line out, then the terminal window does not close.

**Comment by Sawansunar56** [comment]
Okay, your latest commit did something to the live grep. I tried looking into it but I couldn't solve it at all but after reverting, to `2e09fa0` and then removing `vim.api.nvim_win_close()`,  it fixed the problem for both of them. 

If it helps, the error was something like this for live grep, something to do with the wrapper getting wrong number of arguments.
![Screenshot 2023-09-18 203500](https://github.com/jake-stewart/jfind.nvim/assets/62794662/b57730ef-b77e-4461-b54d-fbcf87cca3ab)

**Comment by Sawansunar56** [comment]
> @Sawansunar56 do you possibly have an autocommand which automatically closes terminal windows?

I am using lazy and have set jfind's event to "VeryLazy" but I do not think that is a problem because I have that setting enabled way before this problem started.

Edit: tried removing  the event entirely and the problem persists.

**Comment by jake-stewart** [comment]
@Sawansunar56 could you send your full config?

**Comment by Sawansunar56** [comment]
You can check out my github. Though I am doing something weird so don't judge.

**Comment by jake-stewart** [comment]
i cloned your repo and i can reproduce the bug !!!!!!!!

i'll let you know when i figure it out

**Comment by Sawansunar56** [comment]
I appreciate you taking the time to do all this. Thanks man

**Comment by jake-stewart** [comment]
no worries, thanks for being patient and helpful this whole time.

i put `enabled = false` into `nvchad-term.lua` and jfind stops being broken for me. i will investigate why

EDIT:
may have something to do with these:
```
autoclose_on_quit = {
        enabled = false,
}
close_on_exit = true,
```

**Comment by jake-stewart** [comment]
ideally, jfind would work alongside `nvchad-terminal.lua`. i will attempt to query whether the window is closed before closing it.

**Comment by Sawansunar56** [comment]
> no worries, thanks for being patient and helpful this whole time.
> 
> i put `enabled = false` into `nvchad-term.lua` and jfind stops being broken for me. i will investigate why

Same for me. This is very weird!

**Comment by jake-stewart** [comment]
well, it's fixed now regardless. i wrapped the window close in a pcall so that it fails silently. now you should be able to use nvim and nvchad term side by side! let me know if it all works and ill close the issue

**Comment by Sawansunar56** [comment]
Works fine for find files but the live grep is still the same.

**Comment by jake-stewart** [comment]
@Sawansunar56 try now

**Comment by Sawansunar56** [comment]
Everything seems to be good now. Thanks.
